views/auth_views.py
import flask
from flask import Blueprint, render_template, redirect, request
from flask_login import login_required, logout_user

from view_models.auth.regiser_view_model import RegisterViewModel
from view_models.auth.login_view_model import LoginViewModel
from view_models.auth.forgot_psd_view_model import ForgotPsdViewModel
from view_models.auth.reset_password_view_model import ResetPasswordViewModel
from services import auth_service

auth = Blueprint("auth", __name__, static_folder="static", template_folder="templates")


@auth.get("/login")
def login():
    return render_template("auth/login.html")


@auth.post("/login")
def login_post():
    user_vm = LoginViewModel.validate()
    if not auth_service.validate_captcha():
        flask.abort(401)
    if user_vm.errors:
        return render_template("auth/login.html", errors=user_vm.to_dict().get("errors"))

    return auth_service.login(user_vm)


@auth.get("/register")
def register():
    return render_template("auth/register.html")


@auth.post("/register")
def register_post():
    user_vm = RegisterViewModel().validate()
    if not auth_service.validate_captcha():
        flask.abort(401)
    if user_vm.errors:
        return render_template("auth/register.html", errors=user_vm.to_dict().get("errors"))
    auth_service.add_user(user_vm)

    return redirect('login')


@auth.get("/confirm_account/<token>")
def confirm_acc(token=""):
    return auth_service.confirm_account(str(token))


@auth.get("/forgot_password")
def forgot_password():
    return render_template("auth/forgot_password.html")


@auth.post("/forgot_password")
def forgot_password_post():
    user_vm = ForgotPsdViewModel.validate()
    if not auth_service.validate_captcha():
        flask.abort(401)
    if user_vm.errors:
        return render_template("auth/forgot_password.html", errors=user_vm.to_dict().get("errors"))
    auth_service.sent_reset_link(user_vm)
    return redirect("/")


@auth.get("/reset_password/<token>")
def reset_password(token=""):
    if not auth_service.verify_token(token):
        return redirect("/")
    return render_template("auth/reset_password.html")


@auth.post("/reset_password/<token>")
def reset_password_post(token=""):
    if not auth_service.verify_token(token):
        return redirect("/")
    user_vm = ResetPasswordViewModel.validate()
    if user_vm.errors:
        return render_template("auth/reset_password.html", errors=user_vm.to_dict().get("errors"))
    return auth_service.reset_password(token, user_vm)

@auth.get("/logout")
@login_required
def logout():
    logout_user()
    return redirect('login')

views/home_views.py
import os

import flask
from flask import Blueprint, render_template, request, make_response, Response
from services import home_service
from utils.other_utilities import htmx_request
from datetime import date
from view_models.home.add_review_view_model import AddReviewViewModel
from view_models.home.add_reply_view_model import AddReplyViewModel
from flask_login import current_user, login_required

home = Blueprint("home", __name__, static_folder="static", template_folder="templates")


@home.get("/")
def index():
    top_rated = home_service.get_top_rated_movies()
    top_rated_images = []

    if top_rated:
        for movie in top_rated:
            image_path = os.path.join('static', 'media', 'posters', f"{movie['movie_id']}.png")
            if not os.path.isfile(image_path):
                image_path = "/static/media/placeholder.png"
            else:
                image_path = "/" + image_path
            top_rated_images.append(image_path)

    new_images = []
    new_movies = home_service.get_new_movies()
    if new_movies:
        for movie in new_movies:
            image_path = os.path.join('static', 'media', 'posters', f"{movie['movie_id']}.png")
            if not os.path.isfile(image_path):
                image_path = "/static/media/placeholder.png"
            else:
                image_path = "/" + image_path
            new_images.append(image_path)


    return render_template("home/index.html", top_images=top_rated_images, top_movies=top_rated,
                           new_images=new_images, new_movies=new_movies)




@home.get("/search")
def search():
    query = request.args.get("query", None)
    if "Hx-Request" in request.headers:
        movies = None
        if query:
            movies = home_service.get_movies(query)
        images = None
        ratings = None
        if movies:
            images = home_service.get_images(movies)
            ratings = []
            for movie in movies:
                avg, c = home_service.get_movie_stats(movie.id)
                ratings.append(avg)
        return render_template("home/partials/movie_search_result.html", movies=movies, images=images, ratings=ratings)
    return render_template("home/search.html")


@home.get("/search/page/<int:page>")
@htmx_request
def next_page(page):
    query = request.args.get("query", None)
    movies = None
    ratings = None
    if query:
        movies = home_service.get_movies(query, page)

    images = None
    if movies:
        images = home_service.get_images(movies)
        ratings = []
        for movie in movies:
            avg, c = home_service.get_movie_stats(movie.id)
            ratings.append(avg)
    return render_template("home/partials/movie_search_result.html", movies=movies, images=images, ratings=ratings)


@home.get("/movie/<int:m_id>")
def movie_page(m_id):

    movie = home_service.get_movie(m_id)

    if not movie:
        flask.abort(404)

    avg, rev_count = home_service.get_movie_stats(m_id)
    text_count = home_service.count_reviews(m_id)

    image_path = os.path.join('static', 'media', 'posters', f'{m_id}.png')
    if not os.path.isfile(image_path):
        image_path = "/static/media/placeholder.png"
    else:
        image_path = "/" + image_path

    return render_template("home/movie_page.html", movie=movie, image=image_path,  avg=avg, count=rev_count, text_count=text_count)


@home.get("/get_review_box/<int:m_id>")
@htmx_request
def get_review_box(m_id):

    movie = home_service.get_movie(m_id)
    today = date.today()

    if not current_user.is_authenticated:
        return render_template("home/partials/add_review.html", movie=movie, today=today)

    user_review = home_service.find_user_review(m_id, current_user.id)

    if user_review:
        return render_template("home/partials/user_review.html", movie=movie, review=user_review)

    return render_template("home/partials/add_review.html", movie=movie, today=today)


@home.post("/add_review/<int:m_id>")
@htmx_request
@login_required
def add_review(m_id):
    review = AddReviewViewModel()
    user_review=home_service.add_review(review, m_id)
    movie = home_service.get_movie(m_id)
    response = make_response(render_template("home/partials/user_review.html", movie=movie, review=user_review))
    response.headers["HX-Trigger"] = "ratingUpdate"
    return response


@home.get("/edit_review/<int:r_id>")
@htmx_request
@login_required
def edit_review(r_id):
    review = home_service.get_review(r_id)
    return render_template("home/partials/edit_review.html", review=review)


@home.post("/edit_review/<int:r_id>")
@htmx_request
@login_required
def edit_review_post(r_id):
    review_vm = AddReviewViewModel()
    review = home_service.edit_review(review_vm, r_id)
    response=make_response(render_template("home/partials/user_review.html", review=review))
    response.headers["HX-Trigger"] = "ratingUpdate"
    return response


@home.get("/get_my_review/<int:r_id>")
@htmx_request
@login_required
def get_my_rev(r_id):
    review = home_service.get_review(r_id)
    return render_template("home/partials/user_review.html", review=review)


@home.get("/delete_review/<int:r_id>")
@htmx_request
@login_required
def delete_review(r_id):
    review = home_service.get_review(r_id)
    return render_template("home/partials/delete_review.html", review=review)


@home.post("/delete_review/<int:r_id>")
@htmx_request
@login_required
def delete_review_post(r_id):
    m_id = home_service.delete_review(r_id)
    today = date.today()
    movie = home_service.get_movie(m_id)
    response=make_response(render_template("home/partials/add_review.html", movie=movie, today=today))
    response.headers["HX-Trigger"] = "ratingUpdate"
    return response


@home.get("/update_reviews/<int:m_id>")
@htmx_request
def update_reviews(m_id):
    avg, rev_count = home_service.get_movie_stats(m_id)
    return render_template("home/partials/rating_card.html", avg=avg, count=rev_count)


###################################################
# Reviews
###################################################

@home.get("/reviews/<int:m_id>")
def get_reviews_for_movie(m_id):
    movie = home_service.get_movie(m_id)
    reviews = home_service.get_movie_reviews(m_id)
    avg, rev_count = home_service.get_movie_stats(m_id)
    image_path = os.path.join('static', 'media', 'posters', f'{m_id}.png')
    if not os.path.isfile(image_path):
        image_path = "/static/media/placeholder.png"
    else:
        image_path = "/" + image_path

    return render_template("home/movie_reviews.html", movie=movie, reviews=reviews, image=image_path, avg=avg)


@home.get("/review/<int:r_id>")
def review_page(r_id):
    review = home_service.get_review(r_id)
    if not review:
        flask.abort(404)
    movie = home_service.get_movie(review.movie_id)
    user = home_service.get_user(review.user_id)
    avg, rev_count = home_service.get_movie_stats(movie.id)
    image_path = os.path.join('static', 'media', 'posters', f'{movie.id}.png')
    if not os.path.isfile(image_path):
        image_path = "/static/media/placeholder.png"
    else:
        image_path = "/" + image_path

    return render_template("home/review_page.html", movie=movie, review=review, image=image_path, avg=avg, user=user)


@home.get("/user/<int:u_id>")
def user_profile(u_id):
    user = home_service.get_user(u_id)
    user_reviews = home_service.get_user_reviews(u_id)
    images=[]
    if user_reviews:
        for review in user_reviews:
            image_path = os.path.join('static', 'media', 'posters', f"{review['movie_id']}.png")
            if not os.path.isfile(image_path):
                image_path = "/static/media/placeholder.png"
            else:
                image_path = "/" + image_path
            images.append(image_path)


    return render_template("home/user_profile.html", user=user, reviews=user_reviews, images=images)


@home.get("/reply_box/<int:r_id>")
@htmx_request
def get_reply_box(r_id):
    return render_template("home/partials/add_reply.html", r_id=r_id)

@home.post("/add_reply/<int:r_id>")
@htmx_request
@login_required
def add_reply(r_id):
    reply_vm = AddReplyViewModel.validate()

    if reply_vm.errors:
        return render_template("home/partials/add_reply.html", r_id=r_id, errors=reply_vm.to_dict().get("errors"))

    home_service.add_reply(reply_vm,r_id)
    response = make_response(render_template("home/partials/add_reply.html", r_id=r_id, errors=reply_vm.to_dict().get("errors")))
    response.headers["HX-Trigger"] = "repliesUpdate"
    return response


@home.get("/get_replies/<int:r_id>")
@htmx_request
def get_replies(r_id):
    replies = home_service.get_replies_for_review(r_id)

    return render_template("home/partials/replies_for_review.html", replies=replies, rid=r_id)

@home.post("/delete_reply/<int:r_id>")
@htmx_request
@login_required
def delete_reply(r_id):

    home_service.delete_reply(r_id)
    response = Response(status = 204)
    response.headers["HX-Trigger"] = "repliesUpdate"
    return response

templates/shared/navbar.html
<header>
    <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body fixed-top bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">

          <a  href="{{url_for('home.index')}}">
              <img src="{{ url_for('static', filename="graph/icon2.svg") }}" height="40px" width="40px"></a>
          <h4 class="mb-0 pb-0"><a class="text-light" href="{{url_for('home.index')}}">WatchScore</a></h4>


        <button class="navbar-toggler" id="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <i class='bx bx-menu hamburger' id="toggle-menu"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ms-auto">
          <a class="nav-link me-3" href="{{url_for('home.search')}}"><i class='bx bx-search-alt'></i> Szukaj</a>
              {% if current_user.is_authenticated %}
                <a class="nav-link dropdown-toggle"  role="button" data-bs-toggle="dropdown" aria-expanded="false" href="#">{{ current_user.name }}</a>
                  <ul class="dropdown-menu dropdown-menu-end slideIn">
                    {% if current_user.is_admin %}
                      <li><a class="dropdown-item" href="{{url_for('admin.admin_main')}}">Panel Administratora</a></li>
                        <li><hr class="dropdown-divider"></li>
                    {% endif %}


                    <li><a class="dropdown-item" href="/user/{{ current_user.id }}">Moje recenzje</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Wyloguj się</a></li>
                  </ul>
              {% else %}
                  <a class="nav-link" href="{{url_for('auth.login')}}">Zaloguj się</a>
              {% endif %}
          </div>
        </div>
      </div>
    </nav>
</header>

<script>
    let togglenav = document.getElementById("navbar-toggler");
    togglenav.addEventListener("click", ()=>{
        if(togglenav.getAttribute("aria-expanded")==="true") {
            document.getElementById("toggle-menu").classList.add("bx-x");
        }else{
            document.getElementById("toggle-menu").classList.remove("bx-x")
        }
    })
</script>

templates/shared/site_base.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" href="{{url_for('static',filename='graph/logo.svg')}}" type="image/x-icon">
        <!--bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <!--boxicons package-->
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <!--jQuery-->
        <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
         <!--htmx-->
        <script src="https://unpkg.com/htmx.org@1.9.5"></script>
        <!--bootstrap js-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

        <!--other css styles-->
        <link rel="stylesheet" href="{{url_for('static',filename='css/layout.css')}}" >
        <link rel="stylesheet" href="{{url_for('static',filename='css/site.css')}}" >
        <title>
            {% block title %}
            {% endblock %} - WatchScore
        </title>

    </head>

    <body class="d-flex flex-column min-vh-100" >
        {% block nav %}
        {% endblock %}
        <main>
            {% block content %}
            {% endblock %}
        </main>
        <footer class="mt-auto py-1">
            <div class="text-center d-flex justify-content-center align-items-center">
                &copy; {{current_year}} - WatchScore -&nbsp<a class="footer-text">Privacy</a>
            </div>
        </footer>
            {% block script %}
            {% endblock %}
    </body>
</html>